train:
  force_cpu: false
  gpu_count: 1
  gpu_ids: [4]
  batch_size: 32
  eval_batch_size: 32
  num_workers: 4
  pin_memory: true

data:
  train_manifest_csv: cache/ds002336/loso_subjectwise/fold_ds002336_sub01/manifest_train.csv
  val_manifest_csv: cache/ds002336/loso_subjectwise/fold_ds002336_sub01/manifest_val.csv
  test_manifest_csv: cache/ds002336/loso_subjectwise/fold_ds002336_sub01/manifest_test.csv
  root_dir: cache/ds002336
  preload_dataset: true
  eeg_channel_subset: none
  eeg_channel_target_manifest: cache/ds002336/eeg_channels_target.csv
  expected_eeg_shape: [63, 8, 200]
  expected_fmri_shape: [48, 48, 48, 1]
  normalize_eeg: true
  normalize_fmri: true
  eeg_scale: 1.0
  fmri_scale: 1.0
  fmri_input_type: volume
  fmri_target_shape: [48, 48, 48, 1]
  fmri_spatial_strategy: pad_or_crop
  fmri_temporal_strategy: pad_or_crop
  fmri_pad_value: 0.0
  fmri_normalize_nonzero_only: true

eeg_model:
  checkpoint_path: "pretrained_weights/contrastive_best.pth" # 
  in_dim: 200
  out_dim: 200
  d_model: 200
  dim_feedforward: 800
  seq_len: 8
  shared_dim: 256
  private_dim: 256
  band_power_dim: 5
  n_layer: 6
  nhead: 8
  freeze_backbone: false

fmri_model:
  backbone: neurostorm
  checkpoint_path: "pretrained_weights/pt_neurostorm_mae_ratio0.5.ckpt"
  shared_dim: 256
  img_size: [48, 48, 48, 1]
  in_chans: 1
  embed_dim: 36
  first_window_size: [2, 2, 2, 2]
  window_size: [4, 4, 4, 4]
  patch_size: [6, 6, 6, 1]
  depths: [2, 2, 6, 2]
  num_heads: [3, 6, 12, 24]
  c_multiplier: 2
  last_layer_full_MSA: true
  attn_drop_rate: 0.0
  freeze_backbone: false

finetune:
  output_dir: outputs/ds002336/finetune/fold_ds002336_sub01
  contrastive_checkpoint_path: ""
  num_classes: 2
  selection_metric: accuracy
  fusion: eeg_only
  classifier_mode: add
  eeg_baseline:
    enabled: false
    model_name: eegnet # 7 个选项：svm, labram, cbramod, eeg_deformer, eegnet, conformer
    num_classes: 2
    num_channels: 63
    num_timepoints: 200
    load_pretrained_weights: false
    checkpoint_path: ""
  hidden_dim: 128
  dropout: 0.3
  freeze_encoders: false
  epochs: 200
  lr: 3.3444564916820124e-05
  min_lr: 5.0e-05
  weight_decay: 0.01
  grad_clip: 1.0
  early_stop_patience: 35
  early_stop_min_delta: 0.0
  use_amp: true
  amp_dtype: fp16
  log_interval: 100
  eval_interval: 1
  visualization:
    train_curve:
      enabled: false
      output_dir: ""
    confusion_matrix:
      enabled: false