train:
  output_dir: outputs/joint_barlow_twins/pretrain
  force_cpu: false
  gpu_count: 1
  gpu_ids: [3]
  epochs: 200
  batch_size: 512
  eval_batch_size: 512
  num_workers: 8
  pin_memory: true
  lr: 0.0001
  min_lr: 0.00005
  weight_decay: 0.01
  grad_clip: 1.0
  use_amp: true
  amp_dtype: fp16
  temperature: 0.07
  projection_dim: 256
  band_power_loss_weight: 10.0
  separation_loss_weight: 10.0
  head_dropout: 0.0
  log_interval: 200
  eval_interval: 1
  resume_path: ""
  pretrain_objective: barlow_twins
  barlow_lambda_offdiag: 0.005
  barlow_eps: 1.0e-9

data:
  manifest_csv: cache/joint_contrastive/manifest_all.csv
  root_dir: cache/joint_contrastive
  preload_dataset: false
  expected_eeg_shape: [40, 8, 200]
  expected_fmri_shape: [48, 48, 48, 1]
  normalize_eeg: true
  normalize_fmri: true
  eeg_scale: 1.0
  fmri_scale: 1.0
  fmri_input_type: volume
  fmri_target_shape: [48, 48, 48, 1]
  fmri_spatial_strategy: pad_or_crop
  fmri_temporal_strategy: pad_or_crop
  fmri_pad_value: 0.0
  fmri_normalize_nonzero_only: true

eeg_model:
  checkpoint_path: "pretrained_weights/CBraMod_pretrained_weights.pth"
  in_dim: 200
  out_dim: 200
  d_model: 200
  dim_feedforward: 800
  seq_len: 8
  shared_dim: 256
  private_dim: 256
  band_power_dim: 5
  n_layer: 6
  nhead: 8
  freeze_backbone: false

fmri_model:
  backbone: neurostorm
  checkpoint_path: "pretrained_weights/pt_neurostorm_mae_ratio0.5.ckpt"
  shared_dim: 256
  img_size: [48, 48, 48, 1]
  in_chans: 1
  embed_dim: 36
  first_window_size: [2, 2, 2, 1]
  window_size: [4, 4, 4, 1]
  patch_size: [6, 6, 6, 1]
  depths: [2, 2, 6, 2]
  num_heads: [3, 6, 12, 24]
  c_multiplier: 2
  last_layer_full_MSA: true
  attn_drop_rate: 0.0
  freeze_backbone: false
